In [33]:
import numpy as np
import tensorflow as tf

y=wx+b,y再经过激活函数

In [34]:
def method1():
    x1 = 1
    x2 = 0
    x3 = -1
    w1 = -5
    w2 = 0
    w3 = 0
    t = 1
    learnRate = 1
    b = 0
    #更新权重
    for i in range(10):
        print("w1:%s w2:%s w3: %s" % (w1, w2, w3))
        y = np.sign(w1 * x1 + w2 * x2 + w3 * x3 + b)
        if (y != t):
            w1 = w1 + learnRate * (t - y) * x1
            w2 = w2 + learnRate * (t - y) * x2
            w3 = w3 + learnRate * (t - y) * x3
        else:
            print("训练结束")
            break


def method2():
    x = np.array([[1, 0, -1]])  #一行三列
    w = np.array([[-5], [0], [0]])  #三行一列
    b = 0
    learnRate = 1
    t = 1
    for i in range(10):
        print("标签值为：", t)
        print("函数权重为：", w)
        y = np.sign(np.dot(x, w) + b)
        print("训练预测值为：", y)
        if (t != y):
            w = w + learnRate * (t - y) * x.T
        else:
            print("训练完成")
            break


def method3():
    x = tf.constant([[1, 0, -1]])
    w = tf.constant([[-5], [0], [0]])
    learnRate = 1
    t = 1
    b = 0
    for i in range(10):
        print("标签值为：", t)
        print("函数权重为：", w)
        y = tf.sign(tf.matmul(x, w) + b)
        if (t != y):
            w = w + learnRate * (t - y) * tf.reshape(x, (3, 1))
        else:
            print("训练完成")
            break


In [41]:
method2()

标签值为： 1
函数权重为： [[-5]
 [ 0]
 [ 0]]
训练预测值为： [[-1]]
标签值为： 1
函数权重为： [[-3]
 [ 0]
 [-2]]
训练预测值为： [[-1]]
标签值为： 1
函数权重为： [[-1]
 [ 0]
 [-4]]
训练预测值为： [[1]]
训练完成


In [42]:
method3()

标签值为： 1
函数权重为： tf.Tensor(
[[-5]
 [ 0]
 [ 0]], shape=(3, 1), dtype=int32)
标签值为： 1
函数权重为： tf.Tensor(
[[-3]
 [ 0]
 [-2]], shape=(3, 1), dtype=int32)
标签值为： 1
函数权重为： tf.Tensor(
[[-1]
 [ 0]
 [-4]], shape=(3, 1), dtype=int32)
训练完成
